# Generated by Django 5.2 on 2025-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="podcast",
            name="banner_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AddField(
            model_name="podcast",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="podcasts", to="essayApp.tag"
            ),
        ),
    ]
