# Generated by Django 5.2 on 2025-04-06 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0002_tag_podcast_banner_url_podcast_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="podcast",
            name="duration",
            field=models.IntegerField(default=1),
        ),
    ]
