# Generated by Django 5.2 on 2025-04-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0004_essay_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="cotegory",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
