# Generated by Django 5.2 on 2025-04-07 12:25

import django.db.models.deletion
import essayApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0005_essay_cotegory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="essay",
            name="content",
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        unique=True, validators=[essayApp.models.word_count_validator]
                    ),
                ),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="essayApp.essay",
                    ),
                ),
            ],
        ),
    ]
