# Generated by Django 5.2 on 2025-04-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0006_remove_essay_content_paragraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionForEssay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=120)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="essayApp.essay",
                    ),
                ),
            ],
        ),
    ]
