# Generated by Django 5.2 on 2025-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0008_book_bookcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=130),
        ),
    ]
