# Generated by Django 5.2 on 2025-04-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0010_bookthemes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="theme_description",
        ),
    ]
