# Generated by Django 5.2 on 2025-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0017_alter_forumtopic_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forumcomment",
            old_name="user",
            new_name="author",
        ),
    ]
