# Generated by Django 5.0.6 on 2025-04-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0019_forummessage_forumtopic_comments_delete_forumcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumtopic",
            name="comments",
        ),
    ]
