# Generated by Django 5.2 on 2025-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essayApp", "0022_rename_created_at_contactmessage_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="podcast_banners/"
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="duration",
            field=models.PositiveIntegerField(help_text="Duration in minutes"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="tags",
            field=models.ManyToManyField(blank=True, to="essayApp.tag"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="podcast_videos/"),
        ),
    ]
